spring:
  cloud:
    stream:
      function:
        definition : orderSupplier;paymentEventConsumer    // beans defined in config package that are used to publish and consume events
      bindings:
        orderSupplier-out-0:
          destination: order-event       // kafka topic name
                                         // only publishing events to order-event topic
        paymentEventConsumer-in-0:
          destination: payment-event     // kafka topic name
                                         // only consuming events from payment-event topic



server:
  port: 8081